### ISSUE TITLE
Do not start post-processing when simulation fails

### ISSUE THREAD

**Issue by swesonga** [nemocrys/opencgs#2]
When simulation fails (e.g. due to a segmentation fault in ElmerSolver), post processing code will not find the required files and should therefore not be executed. This reduces the number of errors that need to be diagnosed since file not found errors are a symptom of the problem, not the cause. See https://github.com/nemocrys/opencgs/blob/d1db90ee564ad26776bd1060e943a507193529fb/opencgs/sim.py#L189

**Comment by arvedes** [comment]
Hi, thank you for contributing this! The error management should definitely be improved, I'll have a look at this.

Could you find the reason for your sigsegv? In my experience it is a good starting point to look at the mesh.

**Comment by arvedes** [comment]
I now raise an `OpencgsError` if the simulation fails. I hope that makes debugging easier.
